language: ruby
rvm:
  - 2.3.3
notifications:
  email: false
addons:
  code_climate:
    repo_token: 19eacae3f704e69e605854bd8e178e910a808a40ed7de846e87d89a0aec47a0a
after_success:
  - bundle exec codeclimate-test-reporter
cache: bundler
script:
  - bundle exec rspec
sudo: false
