language: ruby
rvm:
  - 2.3.3
notifications:
  email: false
addons:
  code_climate:
    repo_token: 891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
after_success:
  - bundle exec codeclimate-test-reporter
cache: bundler
script:
  - bundle exec rubocop
  - bundle exec rspec
sudo: false
